### ISSUE TITLE
Question: URP Conversion

### ISSUE THREAD

**Issue by dog199200** [Velorexe/unity-geometry-grass-shader#10]
How hard would it be to convert this to the URP? The setup is great, but my entire project is in URP.

**Comment by dog199200** [comment]
Actually, I figured it out. For those who are not the most shader knowledgeable, like myself, here's how to prep the shader to work in URP:

1) Find the "Tags" parameters and add "RenderPipeline" = "UniversalPipeline" too each one. There are 3 separate areas for Tags. 
2) Change "LightMode" = "ForwardBase" (Tags area 1) and "LightMode" = "ForwardAdd" (Tags area 2) into "LightMode" = "UniversalForward". Do not change the last one. "LightMode" = "ShadowCaster" is still supported. 

- At time of writing -
Unity Version: 2021.3.7f1
URP Version: 12.1.7

**Comment by Velorexe** [comment]
Ah, you solved it before I could jump in.
Thanks for posting this, I'll add it to the `README.md` for anyone stumbling on this in the future.

**Comment by jcs090218** [comment]
I tried in the latest version 2023.1.0f1. Unfortunately, it no longer work in that version of URP. ;(
