### ISSUE TITLE
No Color Shown Using Spot light

### ISSUE THREAD

**Issue by ndumais** [Velorexe/unity-geometry-grass-shader#11]
I've looked at Roy Stan's tutorial a bit, and seems like something was done for directional light to work, it does not seem to be the same for point and spot lights. I'm not too familiar with shader work, maybe someone more experienced with would know how to fix this? Or maybe it's a limitation in this case? Thanks!

![image](https://user-images.githubusercontent.com/48096495/206877755-b5536f40-4b2d-4828-949d-f3c62a89bb48.png)

**Comment by ndumais** [comment]
I've been told the ForwardAdd Pass section, that's commented out probably takes care of that, sadly it seems like there was reason why it was commented out, result is different but not the right one.

![image](https://user-images.githubusercontent.com/48096495/206884157-3691310f-12cd-413b-ac90-5b8a80ee9083.png)

**Comment by Velorexe** [comment]
Hi @ndumais 

It's been a while since I've looked at this repository and I've wanted to update it for a while now, but haven't gotten around to doing so. Mostly because the standard render pipeline is really limiting in what it offers in terms of light in the forward rendering pass.

It also doesn't help that Geometry shaders in Unity are really undocumented and not well explored. Hence I was only able to find that in the vertex pass, the information of 4 important lights that affect the mesh are passed. Since I only get the position, intensity and color of these lights, I've limited the shader to use these lights as point lights at all time (since I miss an angle and spread that the spot-light offers).

Now I'm far from being good at writing shaders (far from it, since I'm more into backend), so I'll try to have a look at it in the following week to see if there's a way to make the `ForwardAdd` pass work, but for now I'd cross it out and say it's a limit of Unity's standard forward rendering.

**Comment by Velorexe** [comment]
Hi @ndumais 

Just wanted to give a heads up that I'm still working on this issue and managed to book some progress. I've managed to read the right light information within the `ForwardAdd` pass. Currently this still only works for point lights, but from what I'm reading (and learning), point lights shouldn't be too far off.

![image](https://user-images.githubusercontent.com/36154558/207687233-182b3e94-1b1f-44c4-a8e6-bdf2ee29c780.png)

**Comment by ndumais** [comment]
Hey, thanks for the follow up!
Have been procrastinating on doing some follow here cause I've been sick the past 3 days.

Did read your first message, and also consulted with some people about what you were saying, someone said: "The "intensity" of each of those lights has already had all the angle falloff stuff (and cookies) calculated." Wasn't sure what to make of it though and didn't get a reply past that. 

So would a white point light render the grass as green (without any directional lights) ?
That would be already a big step tbh!

**Comment by Velorexe** [comment]
Hahaha, yeah like I said, I'm not too familiar with shaders, just interested in them. I did find the macro they were talking about, a very handy `UNITY_LIGHT_ATTENUATION` macro that does all the light attenuation calculation for you (including cookies, spots, points and the likes). So I've used that in the forward pass and the lighting works correctly now.

Here's an example using no directional light and two spot lights, one of which has a cookie
![image](https://user-images.githubusercontent.com/36154558/207837261-fd8e507c-416b-40af-be83-0604d9350bdc.png)

The only "problem" that remains is that the light has a linear falloff, I'm still trying to make it resemble the default lighting more (which I believe uses an inverse squared falloff technique).

For now you can check if it's a result you're comfortable working with until I've got the inverse squared falloff working. I've setup a branch `feature/forward-add` if you want to test it out.

**Comment by ndumais** [comment]
Definitely usable for prototyping now!


I think shadow casting for grass should be disabled in shader, what do you think?
![image](https://user-images.githubusercontent.com/48096495/207950237-dcbe9548-69ed-494f-8f0c-5e1324a437d7.png)

**Comment by Velorexe** [comment]
Glad that it's usable now!

I've just pushed a change to the Forward Add pragma `#pragma multi_compile_fwdadd` to add shadows (which is the same with `#pragma multi_compile_fwdadd_fullshadows` attached to it) from point and spot lights (+ any additional directional lights).

![image](https://user-images.githubusercontent.com/36154558/207966795-fb179270-17a0-4685-84e7-0eae4de8ade6.png)

If you want the grass to not cast any shadows, but only receive them, you can turn them off in the `Mesh Renderer`, which is Unity's preferred way as well.

![image](https://user-images.githubusercontent.com/36154558/207966898-0ce4a879-a4d7-449f-9400-5702b40de3f3.png)

**Comment by ndumais** [comment]
Hey, just wanted to say a quick thanks, went with your solution and it worked out!
